apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-dashboard-ingress
  labels:
    name: kubeflow-dashboard-ingress
spec:
  rules:
  - host: kubeflow.isight.tactful.ai
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 80
